export const VOTAR = 'VOTAR';
export const SET_SEARCH = 'SET_SEARCH';
export const CONCRETIZAR_VOTO = 'CONCRETIZAR_VOTO';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
